# Site settings
title: inv.alid.pw
email: jrh@joshh.co.uk
description: personal site of Josh Holland
baseurl: "/"
url: "http://inv.alid.pw"
exclude:
  - node_modules
  - Gruntfile.js
  - package.json

# Build settings
markdown: kramdown
